name: Check Markdown files correctness

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Extract links from Markdown texts and check if they are alive
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
  # Lint Markdown files
  # Uses: a custom configuration file
  markdown-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        command: config
        globs: |
         .markdownlint.jsonc
         **/*.md
  # Spellcheck Markdown files using `retext` and `remark`
  # Uses: a custom dictionary file
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tbroadley/spellchecker-cli-action@v1
      with:
        dictionaries: '.github/workflows/dictionary.txt'
        files: "'content/**/*.md'"

